import Head from 'next/head';
import { Box, Flex, Heading, Tab, TabList, TabPanel, TabPanels, Tabs } from '@chakra-ui/react';
import OptimizeForm from '@/components/OptimizeForm';
import BenchmarkForm from '@/components/BenchmarkForm';
import useOptimize from '@/hooks/useOptimize';
import { Algorithm, BenchmarkData, OptimizeData, OptimizeFormData } from '@/types';
import { useEffect, useState } from 'react';
import { useBenchmark } from '@/hooks/useBenchmark';


export default function Home() {
	const { data: optimizeData, fetchData: optimizeFetchData, isLoading: optimizeIsLoading, error: optimizeError } = useOptimize();
	const { data: benchmarkData, fetchData: benchmarkFetchData, isLoading: benchmarkIsLoading, error: benchmarkError } = useBenchmark();

	useEffect(() => {
		if (optimizeData) {
			console.log('optimizeData', optimizeData);
		}
	}, [optimizeData]);


	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box>
				<Flex
					backgroundColor="blue.500"
					color="white"
					alignItems="center"
					justifyContent="center"
					padding={8}
					marginBottom={12}
				>
					<Heading as="h1" size="2xl">
						Optimization challenge
					</Heading>
				</Flex>

				<Flex alignItems="center" justifyContent="center" width="100%">
					<Tabs maxW="40rem" width="100%">
						<TabList>
							<Tab>Calculate</Tab>
							<Tab>Benchmark</Tab>
						</TabList>

						<TabPanels>
							<TabPanel>
								<OptimizeForm onSubmit={data => optimizeFetchData(data)} />
							</TabPanel>
							<TabPanel>
								<BenchmarkForm onSubmit={data => benchmarkFetchData(data)} />
							</TabPanel>
						</TabPanels>
					</Tabs>
				</Flex>
			</Box>
		</>
	);
}
